name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when there is a push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject TRACKING_ID into tracking.js
        run: |
          echo "window.TRACKING_ID = '${{ secrets.TRACKING_ID }}';" > tracking.js  # Create tracking.js with tracking ID

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # The directory to deploy (current directory)
